### ISSUE TITLE
separating out design documents not working on OS X

### ISSUE THREAD

**Issue by gad2103** [danielebailo/couchdb-dump#17] opened 2015-02-15 19:54 UTC
```.. INFO: Separating Design documents
... INFO: Duplicating original file for alteration
... INFO: Stripping _design elements from regular documents
... INFO: Fixing end document
... INFO: Inserting Design documents
... INFO: Successfully imported 0 Design Documents
... INFO: Small dataset. Importing as a single file.
{"error":"bad_request","reason":"Missing JSON list of 'docs'"}```

This is the output i'm getting. I'm wondering it there is something wrong with the sed command?

**Comment by dalgibbard** [comment] 2015-02-15 20:07
Do you have any '_design' docs in your DB? They normally at the start or end of the dumped JSON if that helps.

**Comment by dalgibbard** [comment] 2015-02-15 20:07
Also; try running with 'bash -x <command_here>' to get some debug info :)

**Comment by dalgibbard** [comment] 2015-04-17 19:22
I suspect I hit this issue in a recent run; and it may be a different issue; the actual problem is when the dataset is small enough to be imported in a single job without needing to split it; it doesn't seem to format the file appropriately. If/when I do my next load of dev on this code, i'll look to identify and sort this too :)

**Comment by dalgibbard** [comment] 2015-05-07 14:27
OK so I spent some time testing/debugging this - and I can't reproduce it.

```
[root@server dir]# /root/couchdb-backup.sh -R -H 127.0.0.1 -u admin -p pass -d db2 -f db.nodesign.json
... INFO: Separating Design documents
... INFO: Duplicating original file for alteration
... INFO: Stripping _design elements from regular documents
... INFO: Fixing end document
... INFO: Inserting Design documents
... INFO: Successfully imported 0 Design Documents
... INFO: Small dataset. Importing as a single file.
[]

[root@server dir]# /root/couchdb-backup.sh -R -H 127.0.0.1 -u admin -p pass -d db3 -f db.short2.json
... INFO: Separating Design documents
... INFO: Duplicating original file for alteration
... INFO: Stripping _design elements from regular documents
... INFO: Fixing end document
... INFO: Inserting Design documents
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
104  1357    0    78  106  1279  34090   545k --:--:-- --:--:-- --:--:--  624k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
104  1988    0    74  100  1914  22162   559k --:--:-- --:--:-- --:--:--  934k
... INFO: Successfully imported 2 Design Documents
... INFO: Small dataset. Importing as a single file.
[]

[root@server dir]# /root/couchdb-backup.sh -R -H 127.0.0.1 -u admin -p pass -d db4 -f db.short1.json
... INFO: Separating Design documents
... INFO: Duplicating original file for alteration
... INFO: Stripping _design elements from regular documents
... INFO: Fixing end document
... INFO: Inserting Design documents
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
104  1357    0    78  106  1279  23276   372k --:--:-- --:--:-- --:--:--  416k
... INFO: Successfully imported 1 Design Documents
... INFO: Small dataset. Importing as a single file.
[]
```

So with:
* Small file for import, with two design docs
* Small file for import, with one design doc
* Small file for import with no design docs
No issues were found.

@danielebailo I would suggest we can close this for now, and re-open if it can be reproduced, complete with the output from 'bash -x'.

**Comment by dalgibbard** [comment] 2015-05-07 16:15
Note that i've got a merge pending to fix the incorrect detection of _design docs in #23

**Comment by danielebailo** [comment] 2015-05-08 08:05
Darren,
I just added you as collaborator.
You deserve it for the great work you are doing.
Thanks.
Daniele

Daniele

http://www.danielebailo.it/ <http://danielebailo.wordpress.com/>


2015-05-07 18:15 GMT+02:00 Darren Gibbard <notifications@github.com>:

**Comment by dalgibbard** [comment] 2015-05-08 08:09
Cheers dude :D

**Closed by dalgibbard** 2015-05-08 08:09 UTC
